import 'dart:io';
import 'package:dio/dio.dart';
import '../../models/quiz/quiz_api_models.dart';

/// AI Quiz Generation service — mirrors the website's `quizAiGeneration.ts`.
/// Calls the FastAPI quiz AI service (port 8001) for file upload → generation → fetch.
class QuizAiService {
  /// Base URL for the AI quiz service.
  /// Android emulator uses 10.0.2.2 to reach host localhost.
  static String get baseUrl {
    if (Platform.isAndroid) {
      return 'http://10.0.2.2:8001';
    }
    return 'http://127.0.0.1:8001';
  }

  final Dio _dio = Dio(BaseOptions(
    connectTimeout: const Duration(seconds: 30),
    receiveTimeout: const Duration(seconds: 120),
  ));

  /// AI question type — maps to the FastAPI endpoint params.
  static const List<String> questionTypes = ['MCQ', 'FillBlank', 'Explain'];
  static const List<String> difficulties = ['easy', 'medium', 'hard'];

  /// Full pipeline: upload file → generate → fetch quiz → map to drafts.
  Future<List<AiGeneratedQuestion>> generateQuestions({
    required File file,
    int numQuestions = 5,
    String questionType = 'MCQ',
    String difficulty = 'medium',
  }) async {
    // Step 1: Upload file
    final uploadFd = FormData.fromMap({
      'file': await MultipartFile.fromFile(file.path, filename: file.path.split('/').last),
    });
    final uploadRes = await _dio.post('$baseUrl/api/v1/upload', data: uploadFd);
    final uploadData = uploadRes.data;
    if (uploadData is! Map || !uploadData.containsKey('uploadId')) {
      throw Exception('Upload failed: ${uploadData?['detail'] ?? 'Unknown error'}');
    }
    final uploadId = uploadData['uploadId'] as String;

    // Step 2: Generate
    final genFd = FormData.fromMap({
      'uploadId': uploadId,
      'numQuestions': numQuestions.toString(),
      'questionType': questionType,
      'difficulty': difficulty,
      'saveAsFiles': 'false',
    });
    final genRes = await _dio.post('$baseUrl/api/v1/generate', data: genFd);
    final genData = genRes.data;
    if (genData is! Map || !genData.containsKey('quizId')) {
      throw Exception('Generation failed: ${genData?['detail'] ?? 'Unknown error'}');
    }
    final quizId = genData['quizId'] as String;

    // Step 3: Fetch generated quiz
    final quizRes = await _dio.get('$baseUrl/api/v1/quiz/$quizId');
    final quizData = quizRes.data;
    if (quizData is! Map || !quizData.containsKey('quizId')) {
      throw Exception('Failed to fetch generated quiz');
    }

    // Step 4: Normalize & map
    return _normalizeAiPayload(quizData as Map<String, dynamic>);
  }

  List<AiGeneratedQuestion> _normalizeAiPayload(Map<String, dynamic> payload) {
    final rawQuestions = (payload['questions'] as List?) ?? [];
    final rawAnswerKey = (payload['answerKey'] as List?) ?? [];

    // Build answer lookup
    final answersByQ = <String, Map<String, dynamic>>{};
    for (final a in rawAnswerKey) {
      if (a is Map<String, dynamic> && a['questionId'] != null) {
        answersByQ[a['questionId'].toString()] = a;
      }
    }

    final result = <AiGeneratedQuestion>[];
    for (var i = 0; i < rawQuestions.length; i++) {
      final q = rawQuestions[i];
      if (q is! Map<String, dynamic>) continue;

      final qId = 'Question ${i + 1}';
      final ans = answersByQ[qId];
      final type = (q['type'] ?? 'MCQ') as String;
      final question = (q['question'] ?? '') as String;
      final rawOpts = q['options'];
      final options = rawOpts is List ? rawOpts.map((e) => e.toString()).toList() : <String>[];
      final answer = (ans?['correctAnswer'] ?? ans?['answer'] ?? '') as String;
      final reference = (ans?['reference'] ?? '') as String;

      result.add(AiGeneratedQuestion(
        type: type,
        questionText: question,
        options: options,
        correctAnswer: answer,
        reference: reference,
      ));
    }
    return result;
  }
}

/// Represents a question generated by the AI service.
class AiGeneratedQuestion {
  final String type; // 'MCQ', 'FillBlank', 'Explain'
  final String questionText;
  final List<String> options;
  final String correctAnswer;
  final String reference;

  const AiGeneratedQuestion({
    required this.type,
    required this.questionText,
    this.options = const [],
    this.correctAnswer = '',
    this.reference = '',
  });

  /// Maps this AI question to the QuestionTypeEnum used by the quiz system.
  QuestionTypeEnum get mappedType {
    switch (type) {
      case 'MCQ':
        return QuestionTypeEnum.multipleChoice;
      case 'FillBlank':
        return QuestionTypeEnum.shortAnswer;
      case 'Explain':
        return QuestionTypeEnum.essay;
      default:
        return QuestionTypeEnum.multipleChoice;
    }
  }

  /// Pads MCQ options to at least 4 choices.
  List<String> get paddedOptions {
    final filtered = options.where((e) => e.trim().isNotEmpty).toList();
    while (filtered.length < 4) {
      filtered.add('Option ${String.fromCharCode(65 + filtered.length)}');
    }
    return filtered.take(8).toList();
  }

  /// Guesses the correct MCQ answer index from letter-style answers ('A', 'B', etc.).
  String guessMcqAnswerIndex() {
    final cleaned = correctAnswer.trim().toUpperCase();
    const letterMap = {'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7};
    if (letterMap.containsKey(cleaned) && letterMap[cleaned]! < options.length) {
      return options[letterMap[cleaned]!];
    }
    // Try prefix match
    for (var i = 0; i < options.length; i++) {
      if (options[i].trim().toUpperCase().startsWith('${cleaned})')) {
        return options[i];
      }
    }
    return options.isNotEmpty ? options.first : '';
  }
}
